### PR TITLE
Lituan Lenguaje

### PR DESCRIPTION
**Pull request by alexchwoj**

### CODE REVIEW

**Comment by Southclaws** [comment]
Can you also add an entry to `components/languages.js`? The glyph is `🇱🇹`, thanks for the contribution!

**Comment by AdamsLT** [comment]
Uhh, did you use Google Translate? This is god awful and I can't recommend letting this through.
I'll probably make an actual translation soon.

**Comment by alexchwoj** [comment]
yes, google translate

**Comment by Y-Less** [comment]
We've added a CLA, which basically just means you agree to let us use your work, and put it under an open-source license.  You can [sign it here](https://www.clahub.com/agreements/openmultiplayer/homepage).

However, since this was auto-generated and there's now a new one, I'm just going to close this one.

**Pull request closed without merging**
