### PR TITLE
added a basic progress page that lists current pull requests

### PR DESCRIPTION
**Pull request by Southclaws**
Not styled yet but you get the idea. This provides the community some transparency while the code repository is private.

### CODE REVIEW

**Comment by Southclaws** [comment]
image

**Comment by Y-Less** [comment]
What about issues?  Could do the same for them.  I think is should also be based on labels to control which are shown - only any with `public` are exposed, so the default is hidden, but it is easy to add.

**Comment by Southclaws** [comment]
Yeah that sounds good, I wasn't sure if we wanted to public everything right now so I was waiting for your review. I'll add a `public` filter and then we can open it up to the world.

Regarding issues, I can add those easily I think and mix them in with the other items and style it like a form of timeline.

**Comment by Southclaws** [comment]
image

**Pull request merged**
