### PR TITLE
Removes the doubled up disclaimer on FAQ page

### PR DESCRIPTION
**Pull request by jtylr**

### CODE REVIEW

**Review by Southclaws — APPROVED** [review]

**Comment by Southclaws** [comment]
`  5:10  error  'FooterContent' is defined but never used  no-unused-vars`

**Comment by jtylr** [comment]
Oops, I'll fix when I get home. Think it just needs removing from the top of the file. Perils of a commit right before bed.

**Comment by jtylr** [comment]
@Southclaws Totally forgot about this one sorry, is it superseded by #130? If so, should we close this?

**Comment by Southclaws** [comment]
Yeah, I ended up fixing it in that PR anyway 👍

**Pull request closed without merging**
