### PR TITLE
cheap mexican proof-reading service

### PR DESCRIPTION
**Pull request by hotspicytaco**
corrected a few typos, adapted a few words/sentences to sound more clear and natural to native speakers -- recently added questions to be translated later

### CODE REVIEW

**Review by Southclaws — APPROVED** [review]

**Comment by Y-Less** [comment]
Thank you for this.  One small question - I'm honestly oblivious to the answer.  How different are Mexican Spanish and Spanish Spanish?  You changed some bits to sound more natural, would they be said differently in Spain?

**Comment by hotspicytaco** [comment]
Hi! Yes.

The Spanish language is the same in Spain and in Latin America. Meaning, grammatically correct Spanish will be understood in all Spanish speaking countries. What changes from region to region -- not only from country to country -- are the idioms, the pronunciation, the accents, etc. Just think of what happens with English from Great Britain and English in the US. 

I didn't use any exclusive words from Mexico when I revised the previous one. It could be easily understood by anyone right now. A few might stumble with a word or phrase they don’t know, but I think that is normal. It is developers' jargon, e.g. differentiating client and server.

Translating things "as is", word-by-word, makes it sound unnatural to native speakers. It is important to convey the sense of the text and it should always be kept in mind the actual meaning of the original text should never get deviated and even if there is any addition or deletion to the modified matter, it should be done in strict accordance with the subject.

**Comment by Y-Less** [comment]
I knew the grammar would be basically the same, but I didn't know what you had changed exactly.  I'm perfectly happy with your explanation though.  Thank you very much for doing this!

**Comment by Southclaws** [comment]
Thanks!

**Pull request merged**
