### PR TITLE
Add Serbian.jsx

### PR DESCRIPTION
**Pull request by Kuzmanovich**

### CODE REVIEW

**Comment by staticxterm** [comment]
This is a blatant 1:1 copy of my translation along with a "typo" I made in my first commit. You could've at least gone through the trouble of translating yourself because my translation is a loose one, instead of just converting everything I typed in there into Cyrillic.

**Comment by Kuzmanovich** [comment]
> This is a blatant 1:1 copy of my translation along with a "typo" I made in my first commit. You could've at least gone through the trouble of translating yourself because my translation is a loose one, instead of just converting everything I typed in there into Cyrillic.

I don't know what is problem in that because words are pretty much the same, altough I changed some words.
 I just wanted to open.mp be on Serbian cyrillic, that's all.

**Comment by staticxterm** [comment]
The problem with that is you didn't even acknowledge it was me who did the translation in the first place, wasting God knows how many hours doing it. If you put any comment it was based on my original translation, I would have been fine with that. There are some words and sentence structures which work only in Croatian and feel weird in another language and vice-versa, and I believe you did a really, really bad job there.

**Comment by Southclaws** [comment]
@Daksyy @staticxterm I know this is an old PR but it would be great to get Serbian Cyrillic.

What was the actual issue with the PR? My knowledge of the Serbo-Croatian is very lacking but I understand that @staticxterm has written the original Croatian translation (Thanks!) then @Daksyy has transliterated this text into the Serbian Cyrillic writing system and the dispute is that:

1. No credit was given in the commit message or PR message
2. The transliteration from one writing system to another is of poor quality

Am I understanding correct?

If so, I'd like to push this forward and get it to a point where we're all happy to get a Serbian Cyrillic text onto the site.

Thanks for understanding, I hope we can work this out!

**Comment by Southclaws** [comment]
Another thing worth noting, I recently changed the underlying text content files to use a format called Markdown which is much simpler to read and write compared to the old files.

Please check out the readme and read the updated section on translating: https://github.com/openmultiplayer/homepage#translating

**Comment by staticxterm** [comment]
@Southclaws Hello, I am still here.

Yes, you are right in what you have stated. He transliterated the text from Croatian to Serbian Cyrillic based on **my** original translation, without changing the wording of the sentences (they are not a direct translation from English to Croatian and I "sugarcoated" some of them, so I know not any person speaking in Serbian would directly translate it like that).

With that being said, I agree that it would be nice to have this translation as well, but I don't agree on the fact that it's literally a copy of my work, only transliterated, and I'm being given no credit for it!

I'll be sure to check out new format for the language files and come with new pull requests. Thanks for the heads up and keep up the great work!

~Virtual1ty

**Pull request closed without merging**
