### PR TITLE
Update branding

### PR DESCRIPTION
**Pull request by Southclaws**
image

### CODE REVIEW

**Comment by AGraber** [comment]
Looks more colorful and blends nicely with the background

**Comment by Y-Less** [comment]
I liked the old avatar more - the `.mp` in a circle for the `O`, and not purple.

**Comment by Southclaws** [comment]
I will add back the ring as it was a nice substitute for the "Open" in the small logo/icon.

As for the purple, I was a fan of this but open to change! Do you have any suggestions for a replacement "primary" colour to represent the project?

**Comment by Southclaws** [comment]
Ring is back!

image

As for colours, refer to https://github.com/openmultiplayer/graphics/issues/2

**Review by jtylr — APPROVED** [review]

**Review by ADRFranklin — APPROVED** [review]
I can agree with these changes, I don't mind which logo is used as this is only a temp website.

**Comment by Southclaws** [comment]
I'll probably switch to [the light blue](https://github.com/openmultiplayer/graphics/issues/2#issuecomment-491497929) as it's more balanced on both dark and light backgrounds, but aside from that it would be nice to get this merged finally!

**Comment by Southclaws** [comment]
image
With the lighter shade.

**Comment by jtylr** [comment]
LGTM 👍

**Pull request merged**
