### PR TITLE
Polish translation

### PR DESCRIPTION
**Pull request by NatsuEtherious**

### CODE REVIEW

**Comment by Y-Less** [comment]
We've added a CLA, which basically just means you agree to let us use your work, and put it under an open-source license.  You can [sign it here](https://www.clahub.com/agreements/openmultiplayer/homepage).

**Comment by NatsuEtherious** [comment]
> We've added a CLA, which basically just means you agree to let us use your work, and put it under an open-source license. You can [sign it here](https://www.clahub.com/agreements/openmultiplayer/homepage).

Done.

**Comment by Southclaws** [comment]
Could you also add an entry to `components/languages.js`? `"pl": "Polish"` should do

**Comment by Southclaws** [comment]
I've merged #41 now because I had to merge one so I picked at random.

Please rebase on top of this and then justify your changes. Please note that both Y_Less and I do not speak any Polish so we cannot really verify your translations in terms of correct grammar and vocabulary so please liaise with @Jedrzej94 regarding changes.

**Comment by Zbyss** [comment]
Current translation looks like Google Translate output or something, half of this text doesn't really make any sense. The one provided by @NatsuEtherious looks much better in my opinion and it should be the official translation.

**Comment by 0x042** [comment]
So, current translate avaliable at open.mp looks like shit and for sure it is Google Translate output - cuz' it's doesn't make any sense however person who make it - gg, congratz boi. I'm sure that translate provided by @NatsuEtherious is 100 precent corrent cuz' it's been checked for few times.

**Comment by Southclaws** [comment]
I'm happy to merge an updated translation! But this PR needs to be rebased on the current `master` branch state before it can be reviewed.

**Review by Southclaws — APPROVED** [review]

**Comment by Southclaws** [comment]
LGTM - needs a rebase.

**Comment by Southclaws** [comment]
Since this PR seemed dead and required a rebase, I've done it with Markdown: #117

**Pull request closed without merging**
