### PR TITLE
Spelling correction for Hungarian language

### PR DESCRIPTION
**Pull request by ghost**
(I'm sorry for the previous closed pull-request, still don't know how github works exactly.)

### CODE REVIEW

**Comment by Y-Less** [comment]
Could you also sign the CLA please?  It basically just says that you agree to us using your stuff and making it open-source.

**Comment by ghost** [comment]
Done, my bad.

**Review by Southclaws — APPROVED** [review]

**Comment by Y-Less** [comment]
Not "your bad", it wasn't a complaint - you didn't do anything wrong!  We don't expect everyone to know the intricacies of our submission system.

**Comment by Y-Less** [comment]
Thank you very much for the corrections.

**Pull request merged**
