### PR TITLE
Lang ukrainian

### PR DESCRIPTION
**Pull request by Southclaws**

### CODE REVIEW

**Comment by Southclaws** [comment]
Requires some syntax errors to be fixed.

**Comment by m1n1vv** [comment]
Which lines?

**Comment by Southclaws** [comment]
See errors here: https://travis-ci.org/openmultiplayer/homepage/builds/524347666?utm_source=github_status&utm_medium=notification

**Comment by Southclaws** [comment]
To validate locally, you must run `npm install && npm test` - this is easier if you have a proper editor like vscode with JS language integration.

**Comment by m1n1vv** [comment]
I do not have permission to edit Ukrainian. jsx

**Comment by Y-Less** [comment]
Sure you do.  I give you permission.

**Comment by m1n1vv** [comment]
Give me a link to this file

**Comment by Southclaws** [comment]
Don't worry I'll fix this later today.

I merged both your PRs into a separate branch so I could fix it manually and get it merged asap.

**Comment by m1n1vv** [comment]
Thank you very much

**Pull request merged**
