### PR TITLE
Ukrainian language

### PR DESCRIPTION
**Pull request by m1n1vv**
Add: "UA" (Ukraine) language

### CODE REVIEW

**Comment by Brunoo16** [comment]
A CLA was added, and that means you agree to have your work used by us and to be put under an open-source license. 

You can sign it by clicking here: [sign](https://www.clahub.com/agreements/openmultiplayer/homepage)

Also, make sure to add an entry to components/languages.js

**Comment by Daniel-Cortez** [comment]
@m1n1vv The language files are named after the languages, not countries. You'll want to rename your file to "Ukrainian.jsx".

**Comment by Y-Less** [comment]
You also need to add this language to the list in languages.jsx.

**Comment by m1n1vv** [comment]
Excuse me, that so long. I followed the elections in my country )

**Comment by Daniel-Cortez** [comment]
Participating in elections usually doesn't take 3 days, you know :)
Anyway, as Y_Less pointed out, you'll have to make one small modification in `languages.jsx` to add your language to the list (for example, here's a commit that adds Vietnamese language: https://github.com/openmultiplayer/homepage/commit/befd22ffd30eafe9cc436de7e3f3d30249d09642; you'll have to do the same for Ukrainian). After that this PR should be ready to be merged.

**Comment by m1n1vv** [comment]
Did already. I watch after a political situation every day.

**Comment by Daniel-Cortez** [comment]
Err... No you didn't?
The ['Files Changed' tab](https://github.com/openmultiplayer/homepage/pull/44/files) only shows `Ukrainian.jsx`. If you really think you did the change to `languages.jsx`, then you probably forgot to commit or push it.

**Comment by m1n1vv** [comment]
[5aabdee](https://github.com/openmultiplayer/homepage/pull/82/commits/5aabdee7fd9fad288b82376356d86beaab680c6d)

**Comment by Daniel-Cortez** [comment]
Oh, ok then. Why did you have to do it in a separate PR though?

**Comment by Southclaws** [comment]
Do it in this PR.

**Comment by m1n1vv** [comment]
How?

**Comment by Southclaws** [comment]
Just push more commits to your fork, exact same process as what you did to make these changes in the first place.

**Comment by m1n1vv** [comment]
I can't

**Comment by m1n1vv** [comment]
I don't understand how

**Comment by Southclaws** [comment]
it's no different to what you already did, you just add the change, `git add .` `git commit -m"added to languages.js"` and `git push`.

**Comment by m1n1vv** [comment]
I don't use the console

**Comment by Daniel-Cortez** [comment]
Then what do you use?

**Comment by m1n1vv** [comment]
Browser. I practically do't use the github

**Comment by Southclaws** [comment]
Ah, I just noticed your branch name is `patch-1` which is the default branch name for the web interface.

No worries, I've merged into a temporary branch where I'll add the language change myself.

Thanks for your contribution!

**Pull request merged**
